### ISSUE TITLE
...lost (x) runs

### ISSUE THREAD

**Issue by ynot01** [ApexPredator13/Nldb3#1]
![vc3WXFC](https://user-images.githubusercontent.com/28408322/77575825-7b477e00-6eaa-11ea-91b3-77587c867a58.png)

doesn't really make sense to lose a decimal amount of runs and im sure NL has died more than once anyways; unless this was intended to be a % of runs lost?

**Comment by ApexPredator13** [comment]
Hi! You are indeed correct - it's supposed to say "x.xx% chance of losing". Should be fixed now. Thanks for letting me know!
