### ISSUE TITLE
Random episode generator suggestion

### ISSUE THREAD

**Issue by MilanBandic** [ApexPredator13/Nldb3#6]
A couple of months ago, I was playing "NL Bingo" with my friend. It's a game we made up and we recently found that the "all videos" option on the random episode generator was missing. 
We thought that it was a really fun option on the website and just wanted to let you know that we appreciated it.
If you have the time or the will, we would really appreciate if you could add it back.

Thank you for reading :)

**Comment by ApexPredator13** [comment]
Hi!

Thanks for the very nice message! :)

The "all versions" button is now back. 
It should have been there in the first place, leaving it out was an oversight on my part.

Have fun playing bingo!
